### ISSUE TITLE
Respect `editor.lineNumbers`

### ISSUE THREAD

**Issue by jackfranklin** [aioutecism/amVim-for-VSCode#214]
Hello,

Firstly, thank you for the great plugin! I've really enjoyed using it :)

I tried to turn off line numbers by setting `editor.lineNumbers` but it seems that amVim brings them back, always. Is there any chance we could respect that config setting?

Thanks,

Jack

**Comment by aioutecism** [comment]
Oh, this is a bug relating to `amVim.smartRelativeLineNumbers` option.
I'll fix it very soon.

**Comment by jackfranklin** [comment]
I would be happy to attempt a PR to fix this if you can point me in the right direction, also, but I'm not quite sure where to start.

**Comment by jackfranklin** [comment]
@aioutecism thank you for the super speedy reply!

**Comment by aioutecism** [comment]
@jackfranklin 
I'm very happy you'd like to contribute!

Here is some context for you to start:

We added an option to switch between Relative and Absolute line numbers in this PR: #201.

The bug is that I forgot to check if the current `activeTextEditor.options.lineNumbers` is `TextEditorLineNumbersStyle.Off` in this file:
https://github.com/aioutecism/amVim-for-VSCode/blob/master/src/Actions/RelativeLineNumbers.ts

Adding the check in both `on` and `off` methods should fix this issue.


Please feel free to ask if you need further information.

**Comment by aioutecism** [comment]
Released in 1.29.1.
