### ISSUE TITLE
/ search jumps to end of next match, should jump to beginning

### ISSUE THREAD

**Issue by jedwards1211** [aioutecism/amVim-for-VSCode#261]
Using `/` and `n` to search jumps to the end of the next match (due to using VSCode's own find feature I guess).  Vim always jumps to the start of the next match.

This is a dealbreaker for me, because I often do minor search and replace by doing a `c`-replacement, then searching `/` and repeating the replacement with a couple of `n.n.n.` keystrokes.

**Comment by alisonatwork** [comment]
The reason why it appears to be implemented this way is because the search always starts from the current cursor position, so if look for the "next" match, then you will just end up at the same match you just left (assuming you hit `n` several times without changing anything). I notice that this is not the case for `N`, which does set the cursor to the expected position at the start of the match. This might be something we can work around.

**Comment by alisonatwork** [comment]
Hi @jedwards1211 I have a proposal to fix this on PR #289 - could you perhaps help out with some testing?

**Comment by jedwards1211** [comment]
Well, I don't use amVim, I had just tried it out, stumbled into this issue, reported it, and decided to go back to VSCodeVim.  So I'm too busy for it to be worth working on, I'm afraid

**Comment by alisonatwork** [comment]
I understand. Thanks for the bug report and helping to improve the plugin!
