### ISSUE TITLE
Vgg does not work

### ISSUE THREAD

**Issue by cpetrov** [aioutecism/amVim-for-VSCode#292]
`gg` does not work in visual mode.

Example document:

```
1
2
3
```
Go to line 3. Press `V`. amVim will enter visual mode. Press `gg`. The cursor should jump to the first line, but it doesn't.

**Comment by alisonatwork** [comment]
Great bug report, thanks @cpetrov.

It seems the ROT13 feature of #235 has hijacked the `g` motions in visual mode. This is a similar problem to what we had with `gD` and `gd` in the first iteration, before we refactored that into a motion.

@mtsknn I think it would be better to revert the ROT13 change for now so that `gg` and other motions continue to work in visual mode. To be honest, the `g?` command doesn't work for me in visual mode either in the current HEAD. Are you interested to work on a patch for that?

**Comment by alisonatwork** [comment]
@cpetrov I have now fixed this in master. Can you compile and check master? Otherwise it should be released in the next version as per #291 (CC: @aioutecism)

**Comment by cpetrov** [comment]
@alisonatwork It works! Thank you!

**Comment by mtsknn** [comment]
Heh, I don't know if there's any practical use for `g?` so removing the feature is fine for me. 😄 I don't use it myself (despite having implemented it in 2019) so I'm not interested in re-implementing it unless there's demand for it.
