### ISSUE TITLE
apply powerline theme 

### ISSUE THREAD

**Issue by ChemaBautista** [aioutecism/amVim-for-VSCode#297]
apply powerline theme

**Comment by alisonatwork** [comment]
It seems that this ticket is referring to this Vim plugin: https://github.com/powerline/powerline

I am not sure if this is something worthwhile including in amVim-for-VSCode, because the functionality as I understand it should be able to be implemented as an independent VSCode plugin. For instance, VSCode already shows things like the Git branch, file encoding and so on in the status bar, and plugins have the ability to add other information there. In fact, there is already a plugin that provides some of the functionality: https://github.com/pcwalton/vscode-powerline

@ChemaBautista what sort of functionality specifically would you expect to see implemented in amVim here?
