### ISSUE TITLE
Need to mark version in repo with a bumped prerelease number

### ISSUE THREAD

**Issue by ghost** [aioutecism/amVim-for-VSCode#42]
When doing releases, bump the version in the repo to a "pre" version immediately after a release.

For example, right now, the latest release is 0.1.1.  The version in the repo should now be at 0.1.2-pre.  When doing the next release, make one commit changing it to 0.1.2, prepare a build from that, and then immediately make another commit changing the version string in the repo to 0.1.3-pre.

If the next version ends up being 0.2.1 instead of 0.1.2, it's will be okay to change it directly from 0.1.2-pre to 0.2.1.

If you make a build right now, the build and the latest release will be given identical version numbers, but they're not identical builds.

**Comment by aioutecism** [comment]
Thanks for the explanation.
Added `0.1.2` as a pre-release.

**Comment by colbyrussell** [comment]
I only meant the version number in package.json.  Since the current version on marketplace.visualstudio.com is 0.1.1, the package.json in the repo should be at 0.1.2-pre.

**Comment by aioutecism** [comment]
Oh, Visual Studio Market doesn't allow updates without a newer version.
If we merged another branch, should we change the version to `0.1.2-pre2`?

**Comment by colbyrussell** [comment]
I'm not sure what you mean.  This is what I mean:

Right now, marketplace.visualstudio.com has a version 0.1.1.

If you build from the repo right now, you will also get a build that says it's
version 0.1.1 (because that's what it says in the package.json).  But it's not the same.  It's newer.  It should have a newer version number.

**Comment by colbyrussell** [comment]
What you'll want to do, in order to avoid changing the version number in
every commit, is to follow something like this process for every release:

Let's pretend the version we are preparing for release X is 0.0.1.

- Change package.json to the correct version for the current release (0.0.1)
- Tag the commit with that version number
- Build it and publish it in the marketplace
- *Immediately* change package.json to version 0.0.2-pre

Let's pretend some time passes and we are now preparing the next release Y.  It
will be version 0.0.2.

- Change package.json from 0.0.2-pre to 0.0.2
- Tag the commit with that version number
- Build it and publish it in the marketplace
- *Immediately* change package.json to version 0.0.3-pre

Alternatively, if you want to make the version number for Y be 0.1.0 instead
of 0.0.2 (because there were significant changes), then just alter the first
step:

- Change package.json from 0.0.2-pre to 0.1.0

... and the last step:

- *Immediately* change package.js to version 0.1.1-pre

This means anytime you build from the current state of the repo, you won't get
a build with a version number that conflicts with what's in the marketplace.

**Comment by aioutecism** [comment]
I see.

I've just published newest build with 0.1.2 and changed the version to 0.1.3-pre.

**Comment by colbyrussell** [comment]
Thanks.
