### ISSUE TITLE
Future plans and roadmap

### ISSUE THREAD

**Issue by DanEEStar** [aioutecism/amVim-for-VSCode#68]
I really want vim support in VSCode.
This extension is the best I have found so far. But it lacks some of my best liked commands like `ci"`. I know its coming :)

But I would like to work on this extension.
Do you have some future plans and/or a roadmad what you want to tackle next. 
I think a lot of this info is provided in some of your issues.

Do you have some areas where you especially would like some contributions?
One idea I have is to add more unit tests.
Is that something that you would accept?

**Comment by aioutecism** [comment]
You are very welcomed to contribute this project. 

I have to work on weekdays, so the only time I have for this project is early morning before I go to work and weekends. 
I can't promise any plan since I have little time with this project. What I can right now is listen to what people want and add them by desirability. 

When I'm going to start on something, I'll create an issue and assign it to my self, so others won't do the same work again. 
You can just pick from the unassigned issues or anything you want eagerly, and contribute. It should be good if you let me know what you are working on by leaving a comment in that issue. 

And yes! Unit testing is what I'm going to add soon. Can you wait until I built the basic part of test framework and then help adding tests to it?

Basic text objects support is done(#63). I'll merge it and publish a new version today.

**Comment by DanEEStar** [comment]
Do you already have some ideas how to do the test framework?

I think one step would be to split the `Dispatcher` into some vim-extension specific parts, like the input and mode handling and the VSCode specific parts like the command and key registering.

I am very impressed how https://github.com/74th/vscode-vim does some test, by comparing the behavior of the original vim with the extension implementation. 
Something similar for this extension would be great.

**Comment by vavans** [comment]
And if we stick to the same way they describe their tests, like this 
```javascript
MotionTests["charactor motion"] = {
    "l:move to right 1": {
        "in": ["abc| def"],
        "key": "l",
        "out": ["abc |def"]
    },
    "3l:move to right 3": {
        "in": ["a|bcdefg"],
        "key": "3l",
        "out": ["abcd|efg"]
    },
```
we can benefit from each other.

**Comment by aioutecism** [comment]
I'm going to build a "black box" test framework.
It should be very similar to what 74th/vscode-vim is doing, but with multi-cursor tests too.

**Comment by benjaminRomano** [comment]
Hi @aioutecism, I had some freetime and I looked into the testing framework. Here is the code #96.

Currently, amVim isn't easily testable due to the issues in the PR. If you would like, I could attempt to fix these problems and submit a working PR.

**Comment by benjaminRomano** [comment]
@aioutecism have you had a chance to look over the testing framework? If you are too busy atm, I'd be willing to join as a contributor to help with progress.

**Comment by Jayphen** [comment]
Is this still being developed actively?

The primary alternative (VSCodeVim/Vim) is almost unusably slow in comparison to this plugin, but amVim has many missing features.

**Comment by aioutecism** [comment]
Hi @Jayphen,

This is a side project and I'm trying to put as much time as I can to make improvements.

However, everyone uses Vim the unique way and has their favorite features. I can't implement them all by my own with limited time I have for this project.

That said, your help is very much needed. Please open issues for features you want or vote on existing ones to make it clear which feature we should implement next. And, if you will, please open Pull Request and I'll make sure your contributes goes into next update as soon as possible.

Thank you.
