### ISSUE TITLE
"No suggestions." box always present

### ISSUE THREAD

**Issue by hellmean** [aioutecism/amVim-for-VSCode#7]
the subj
the suggestWidget box is always present once you start typing in the INSERT mode, even if there is nothing to suggest (displaying 'No suggestions'). This is an abnormal behavior and does not occur when extension is inactive.

cheers!

**Comment by aioutecism** [comment]
Yes. This is a problem I haven't find a good solution.
I asked for keybinding service support in Microsoft/vscode/issues/1432.
If you have any idea, please let me know.

**Comment by hellmean** [comment]
all i can say is that this very strange as the two other plugins do exactly the same as yours, but for them this does not result in this behavior

**Comment by aioutecism** [comment]
74th's extension uses vscode's selections in normal mode, and only bind keys when there is no selections(Insert mode).
This solves the problem, but has weird apperance and cause the editor to be slow when editing large file.

I'll take a look into the other one.

**Comment by AndersenJ** [comment]
The other extention (vscodevim/Vim) has the same problem; IIRC they decided to wait until MS fixed this behavior.

**Comment by jpoon** [comment]
I'm the maintainer for vscodevim/Vim and just came across this project.

@AndersenJ we programatically show the auto-suggest window following each key press so we have the opposite problem. Rather than showing no auto-suggest window, we *always* show it, even if there is nothing: https://github.com/VSCodeVim/Vim/issues/126

As an aside,

> Because this and this are missing basic functions(such as multi-cursor support) I need. And they need a complete refactoring to meet my needs.

You are absolutely welcome to help contribute to vscodevim. Definitely would be better if we all invested our effort in making one of these extensions better rather than having the mentality: "nope this sucks, i'm going to write my own".

**Comment by aioutecism** [comment]
@jpoon 

Apologize for the offensive words in readme(I edited them), didn't mean it.

I was going to contribute to 74th's extension. However, I found I need to modify almost every file in that project to meet my needs, and it's almost a rewrite.
I therefore decided created a new one to save my efforts.

**Comment by aioutecism** [comment]
This should be solved in 1.0.0.
However, 1.0.0 depends on VSCode >= 0.10.12.
You can download the VSCode insiders version [here](https://code.visualstudio.com/insiders) and install amVim to try it.
